#!/bin/bash

function cconv {
        [[ -z $3 ]] && msg_send "用法：/cconv <从货币> <到货币> <金额>" && exit 0
        rate=$(curl -s 'http://free.currencyconverterapi.com/api/v5/convert?q='$1'_'$2'&compact=y' | jq '.[][]')
        log "cconv: from $1 to $2, amount $3."
        [ -z "$rate" ] && msg_send "没有那种货币。" && exit 0
        result="$(bc <<< "$3 * $rate")"
        [[ ! -z $result ]]&& msg_send "$3$1 = $result$2" || msg_send "？"
        exit 0
}

cconv $cmd_body
