#!/bin/bash

metar_api="https://avwx.rest/api/metar"

msg_send_OPTIONS="parse_mode=Markdown"

[ ! -z "$cmd_body" ] && msg_send "\`$(curl -s "$metar_api/$cmd_body" | jq -cr '."Raw-Report"')\`" || msg_send "用法： \`/metar <ICAO>\`"
